src/app/components/customer/CustomerInfo.tsx, src/app/search/page.tsx, src/components/ui/input.tsx
=> 検索ページとクソ客の情報のコンポーネントを作成

.editorconfig, .prettierrc, docker-compose.yml
editorconfig, prittier, docker-composeファイルを追加
=> configファイル系追加

prisma/migrations/20241120132701_/migration.sql, prisma/migrations/20241120133431_optionize_invitor/migration.sql, prisma/schema.prisma
スキーマのinvitorをオプショナルにしなかったせいでバグりました
（アカウント登録した時点では招待コードを入力してないからオプショナルにしないと怒られる）
=> アカウント登録ができないバグを修正

prisma/schema.prisma
=> スレッド機能に関するスキーマ作成

src/app/lib/auth.ts, src/app/license/actions.ts, src/app/license/page.tsx, src/app/page.tsx, src/app/threads/page.tsx
closes #37 #26 
- #26 
- #37 
- しれっとinvitor → inviter に変更
~~すみません、設定ページのブランチをいったん移動しようとして強制pushしたんですが普通に久米さんのローカルに影響出ますよね...~~ developを強制プッシュしたわけじゃないから大丈夫か
fetchしてうまいことやってください！
=> TOPのリダイレクト処理

package-lock.json, package.json, src/app/components/Header.tsx, src/components/ui/avatar.tsx
=> P042_dropdown

src/app/license/actions.ts
=> 存在しないコードを入力した際にエラーがでるよう修正

src/app/license/actions.ts
=> 招待コードを入力したらuserテーブルのinviterに招待者を追加する処理を記述

src/app/threads/[threadId]/components/ThreadPostDialog.tsx
=> モーダルを閉じた際の自動フォーカスを無効

src/app/threads/[threadId]/components/ThreadConversationList.tsx
=> IDの表示とレイアウト調整

package.json, vercel.json
=> vercelのプレビューでコケるので対応

src/app/components/Header.tsx, src/app/invite/page.tsx, src/app/layout.tsx, src/app/license/components/InviteCodeForm.tsx, src/app/license/page.tsx, src/app/page.tsx, src/app/setting/component/SettingForm.tsx, src/app/setting/page.tsx, src/app/threads/[threadId]/page.tsx, src/app/threads/page.tsx, src/app/utils/metadata.ts
=> 各ページのスタイル調整とOGP設定

docker-compose.yml, package-lock.json, package.json, src/app/license/actions.test.ts, src/app/setting/actions.test.ts, vitest.config.ts
=> P047_vitest

prisma/migrations/20241130172026_/migration.sql, prisma/schema.prisma, src/app/threads/[threadId]/actions.ts, src/app/threads/[threadId]/components/ThreadConversationList.tsx, src/app/threads/[threadId]/components/ThreadReactionButton.tsx, src/app/threads/[threadId]/components/ThreadReactionList.tsx, src/app/threads/[threadId]/components/data/threadReactionList.ts, src/app/threads/[threadId]/schema.ts
=> リアクションボタンの実装

prisma/migrations/20241202145134_/migration.sql, prisma/schema.prisma
=> emailをオプショナルに変更

src/app/page.tsx
=> トップページのスレッド作成ボタンを削除

src/app/threads/[threadId]/components/ThreadReactionButton.tsx
=> ライトモードでホバー時にアクティブなリアクションの文字色が変わっていたため修正

src/app/components/Header.tsx, src/app/components/menu/MenuSlide.tsx, src/app/components/menu/actions.ts, src/app/components/nav/NavMenu.tsx, src/app/lib/auth.ts, src/app/license/actions.test.ts, src/app/license/actions.ts, src/app/license/components/InviteCodeForm.tsx, src/app/mypage/actions.test.ts, src/app/mypage/component/InviteTabs.tsx, src/app/mypage/component/SettingForm.tsx, src/app/mypage/page.tsx, src/app/threads/[threadId]/components/ThreadContentDialog.tsx, src/app/threads/[threadId]/components/ThreadConversationContent.tsx, src/app/threads/[threadId]/components/ThreadConversationList.tsx, src/app/threads/[threadId]/components/ThreadPostButton.tsx, src/app/threads/[threadId]/components/ThreadPostDrawer.tsx, src/app/threads/[threadId]/components/ThreadPostDrawerButton.tsx, src/app/threads/[threadId]/components/ThreadReactionButton.tsx, src/app/threads/[threadId]/components/ThreadReactionList.tsx, src/app/threads/[threadId]/components/data/threadReactionList.ts, src/app/threads/[threadId]/page.tsx, src/app/threads/[threadId]/schema.ts, src/app/threads/[threadId]/utils/splitTextWithMention.test.ts, src/app/threads/[threadId]/utils/splitTextWithMention.ts, src/app/threads/[threadId]/utils/splitTextWithMention.tsx, src/app/threads/components/ThreadDrawer.tsx
=> 主にリプライ機能の作成

src/app/mypage/component/SettingForm.tsx, src/app/threads/[threadId]/components/ThreadContentDialog.tsx, src/app/threads/[threadId]/components/ThreadPostDrawer.tsx, src/app/threads/components/ThreadDrawer.tsx
=> 送信中のスタイルを定義

lefthook.yml, package-lock.json, package.json, src/app/mypage/component/SettingForm.tsx, src/app/threads/[threadId]/components/ThreadPostDrawer.tsx, src/app/threads/[threadId]/components/ThreadReactionButton.tsx, src/app/threads/components/ThreadDrawer.tsx
=> Lefthook設定
